#!/usr/bin/env python

import random

name1 = input("What is your NAME?\n") 
print("Best of Luck!",name1)

def main():
    """Start a guessing music genre"""
    print("\nGuess the music genre! Choose one of music genre : Jazz,Pop,Rock,Balada,HipHop")
    music = ["Jazz","Pop","Rock","Balada","HipHop"]

    hint = random.choice(music)
    print(hint)
    guess = None

    x = 3

    for guess_chance in range(1,4):
        guess = str(input("\nPick a music genre: "))

        if hint != guess:
            x -= 1
            print('You guess ' + guess + '. Unfortunately you got the wrong answer. \nPlease try again! You get ' + str(x) + ' chance left.')
        elif hint == guess:
            print("You guess " + guess + ". Congratulation you got it right!")  
            break 
        else:
            print("Chance remaining =",guess_chance)
            break

    if guess == hint:
        print('Congrats, you guess correctly in ' + str(guess_chance) + ' times.\n')
    else:
     print('Nope, the correct answer is ' + str(hint) + '.\n')
main()